blueprint:
  name: Windows TRV Economy Bio
  description: Force TRV close until windows is open
  domain: automation
  input:
    ieeeaddressoftrv:
      name: IEEE Address
      description: This is the address of the TRV found in your zigbee database example
        0x459877fffe1f2e83
    windowsensor:
      name: Select the window binary sensor
      description: This will be your external window sensor
      selector:
        entity:
          domain: sensor
          device_class: window
          multiple: true
    openingtiming:
      name: Frequency Time
      description: This will set the sleep time in second before considering opened
    closingtiming:
      name: Frequency Time
      description: This will set the sleep time in second before considering closed
    maxtiming:
      name: Frequency Time
      description: This will set the max time before re enabling the normal valve operation
  source_url: https://github.com/faxbio/bluetrvbiosync/blob/main/biottrv.yaml
alias: BIO - Stop TRV on Windows opening
trigger:
- platform: state
  entity_id: binary_sensor.door_window_salotto
  to: 'on'
  for:
    hours: 0
    minutes: 0
    seconds: 30
condition:
- condition: state
  entity_id: input_boolean.estate
  state: 'off'
action:
- service: scene.create
  data:
    scene_id: scntrvsalottofinestra
    snapshot_entities:
    - climate.trv_salotto
- service: mqtt.publish
  data:
    topic: zigbee2mqtt/0x8cf681fffeb0f188/set/force
    payload: close
- wait_for_trigger:
  - platform: state
    entity_id:
    - binary_sensor.door_window_salotto
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  timeout: 00:10:00
- service: mqtt.publish
  data:
    topic: zigbee2mqtt/0x8cf681fffeb0f188/set/force
    payload: normal
- service: scene.turn_on
  data: {}
  target:
    entity_id: scene.scntrvsalottofinestra
mode: restart
