blueprint:
  name: Windows TRV Economy Bio
  description: Force TRV close until windows is open
  domain: automation
  input:
    ieeeaddressoftrv:
      name: IEEE Address
      description: This is the address of the TRV found in your zigbee database example
        0x459877fffe1f2e83
    windowsensor:
      name: Select the window binary sensor
      description: This will be your external window sensor
      selector:
        entity:
          domain: binary_sensor
          #device_class: window
          multiple: true
    summersensor:
      name: Select you summer sensor
      description: This vill pervent the automation to run during summer
      selector:
        entity:
          domain: input_boolean
          multiple: false
    openingtiming:
      name: Opening Time
      description: This will set the sleep time in second before considering opened
    closingtiming:
      name: Closing Time
      description: This will set the sleep time in seconds before considering closed
    maxtiming:
      name: Max Time
      description: This will set the max time in minutes before re enabling the normal valve operation
  source_url: https://github.com/faxbio/bluetrvbiosync/blob/main/biotrvwindow.yaml
alias: BIO - Stop TRV on Windows opening
trigger:
- platform: state
  entity_id: !input 'windowsensor'
  to: 'on'
  for:
    hours: 0
    minutes: 0
    seconds: !input 'openingtiming'
condition:
- condition: state
  entity_id: !input 'summersensor'
  state: 'off'
action:
- service: persistent_notification.create
  data:
    message: 'Window Sensor: {{ windowselected }} Opening detected - Setting TRV on forced CLOSE'
    title: BIO - Windows TRV Thermostat Automation BLUEPRINT
- service: mqtt.publish
  data:
    topic: zigbee2mqtt/{{ target_device }}/set/force
    payload: close
- wait_for_trigger:
  - platform: state
    entity_id: !input 'windowsensor'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: !input 'closingtiming'
  timeout: 00:{{ maxtime }}:00
- service: mqtt.publish
  data:
    topic: zigbee2mqtt/{{ target_device }}/set/force
    payload: normal
- service: persistent_notification.create
  data:
    message: 'Window Sensor: {{ windowselected }} Closing detected - Setting TRV on NORMAL'
    title: BIO - Windows TRV Thermostat Automation BLUEPRINT
variables:
  target_device: !input 'ieeeaddressoftrv'
  windowselected: !input 'windowsensor'
  maxtime: !input 'maxtiming'
